version: "3.9"
services: 
    todo_app_dev:
        build:
            context:
            target: dev
        ports:
            - 5000:5000
        env_file: 
            - .env
        volumes: 
            - ./todo_app:/code/todo_app